void FatJet_tau2_vertexEnergyRatio_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:37 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-1.545455,-1.659967,3.909091,8.793397);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_tau2_vertexEnergyRatio_data__61 = new TH1D("DATA__FatJet_tau2_vertexEnergyRatio_data__61","",12,-1,3.8);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(1,9060);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(3,2195);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(4,3143);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(5,1362);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(6,645);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(7,373);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(8,232);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(9,134);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(10,104);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(11,66);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinContent(12,249);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(1,95.18403);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(3,46.85083);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(4,56.06247);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(5,36.90528);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(6,25.39685);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(7,19.31321);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(8,15.23155);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(9,11.57584);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(10,10.19804);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(11,8.124038);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetBinError(12,15.77973);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetMinimum(0.5);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetMaximum(9.06e+07);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetEntries(17567);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetFillColor(1);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetFillStyle(0);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetMarkerStyle(20);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->SetMarkerSize(0.75);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetTitle("tau2_vertexEnergyRatio");
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetRange(1,100);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetZaxis()->SetTitle("_data");
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data__61->Draw("E1X0");
   
   TH1D *DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62 = new TH1D("DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62","",12,-1,3.8);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(1,9060);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(3,2195);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(4,3143);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(5,1362);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(6,645);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(7,373);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(8,232);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(9,134);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(10,104);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(11,66);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinContent(12,249);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(1,95.18403);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(3,46.85083);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(4,56.06247);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(5,36.90528);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(6,25.39685);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(7,19.31321);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(8,15.23155);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(9,11.57584);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(10,10.19804);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(11,8.124038);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetBinError(12,15.77973);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetMinimum(0.5);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetMaximum(9.06e+07);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetEntries(17567);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetDirectory(0);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetFillColor(1);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetFillStyle(0);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetMarkerStyle(20);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->SetMarkerSize(0.75);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetTitle("tau2_vertexEnergyRatio");
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetRange(1,100);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetZaxis()->SetTitle("_data");
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_tau2_vertexEnergyRatio_data_copy__62->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_tau2_vertexEnergyRatio_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
