void FatJet_prunedMass_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:36 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-29.54546,-1.596582,265.9091,8.369205);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_prunedMass_data__9 = new TH1D("DATA__FatJet_prunedMass_data__9","",20,0,400);
   DATA__FatJet_prunedMass_data__9->SetBinContent(3,1954);
   DATA__FatJet_prunedMass_data__9->SetBinContent(4,3732);
   DATA__FatJet_prunedMass_data__9->SetBinContent(5,3385);
   DATA__FatJet_prunedMass_data__9->SetBinContent(6,2712);
   DATA__FatJet_prunedMass_data__9->SetBinContent(7,2097);
   DATA__FatJet_prunedMass_data__9->SetBinContent(8,1505);
   DATA__FatJet_prunedMass_data__9->SetBinContent(9,973);
   DATA__FatJet_prunedMass_data__9->SetBinContent(10,501);
   DATA__FatJet_prunedMass_data__9->SetBinContent(11,284);
   DATA__FatJet_prunedMass_data__9->SetBinContent(12,179);
   DATA__FatJet_prunedMass_data__9->SetBinContent(13,99);
   DATA__FatJet_prunedMass_data__9->SetBinContent(14,60);
   DATA__FatJet_prunedMass_data__9->SetBinContent(15,36);
   DATA__FatJet_prunedMass_data__9->SetBinContent(16,6);
   DATA__FatJet_prunedMass_data__9->SetBinContent(17,13);
   DATA__FatJet_prunedMass_data__9->SetBinContent(18,6);
   DATA__FatJet_prunedMass_data__9->SetBinContent(19,8);
   DATA__FatJet_prunedMass_data__9->SetBinContent(20,13);
   DATA__FatJet_prunedMass_data__9->SetBinError(3,44.20407);
   DATA__FatJet_prunedMass_data__9->SetBinError(4,61.0901);
   DATA__FatJet_prunedMass_data__9->SetBinError(5,58.18075);
   DATA__FatJet_prunedMass_data__9->SetBinError(6,52.07687);
   DATA__FatJet_prunedMass_data__9->SetBinError(7,45.79301);
   DATA__FatJet_prunedMass_data__9->SetBinError(8,38.79433);
   DATA__FatJet_prunedMass_data__9->SetBinError(9,31.19295);
   DATA__FatJet_prunedMass_data__9->SetBinError(10,22.38303);
   DATA__FatJet_prunedMass_data__9->SetBinError(11,16.8523);
   DATA__FatJet_prunedMass_data__9->SetBinError(12,13.37909);
   DATA__FatJet_prunedMass_data__9->SetBinError(13,9.949874);
   DATA__FatJet_prunedMass_data__9->SetBinError(14,7.745967);
   DATA__FatJet_prunedMass_data__9->SetBinError(15,6);
   DATA__FatJet_prunedMass_data__9->SetBinError(16,2.44949);
   DATA__FatJet_prunedMass_data__9->SetBinError(17,3.605551);
   DATA__FatJet_prunedMass_data__9->SetBinError(18,2.44949);
   DATA__FatJet_prunedMass_data__9->SetBinError(19,2.828427);
   DATA__FatJet_prunedMass_data__9->SetBinError(20,3.605551);
   DATA__FatJet_prunedMass_data__9->SetMinimum(0.5);
   DATA__FatJet_prunedMass_data__9->SetMaximum(3.732e+07);
   DATA__FatJet_prunedMass_data__9->SetEntries(17567);
   DATA__FatJet_prunedMass_data__9->SetFillColor(1);
   DATA__FatJet_prunedMass_data__9->SetFillStyle(0);
   DATA__FatJet_prunedMass_data__9->SetMarkerStyle(20);
   DATA__FatJet_prunedMass_data__9->SetMarkerSize(0.75);
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetTitle("M_{pruned} (AK8 jets) [GeV]");
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetRange(1,13);
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data__9->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data__9->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_prunedMass_data__9->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data__9->GetZaxis()->SetTitle("_data");
   DATA__FatJet_prunedMass_data__9->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data__9->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data__9->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data__9->Draw("E1X0");
   
   TH1D *DATA__FatJet_prunedMass_data_copy__10 = new TH1D("DATA__FatJet_prunedMass_data_copy__10","",20,0,400);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(3,1954);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(4,3732);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(5,3385);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(6,2712);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(7,2097);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(8,1505);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(9,973);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(10,501);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(11,284);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(12,179);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(13,99);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(14,60);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(15,36);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(16,6);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(17,13);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(18,6);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(19,8);
   DATA__FatJet_prunedMass_data_copy__10->SetBinContent(20,13);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(3,44.20407);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(4,61.0901);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(5,58.18075);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(6,52.07687);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(7,45.79301);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(8,38.79433);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(9,31.19295);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(10,22.38303);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(11,16.8523);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(12,13.37909);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(13,9.949874);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(14,7.745967);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(15,6);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(16,2.44949);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(17,3.605551);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(18,2.44949);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(19,2.828427);
   DATA__FatJet_prunedMass_data_copy__10->SetBinError(20,3.605551);
   DATA__FatJet_prunedMass_data_copy__10->SetMinimum(0.5);
   DATA__FatJet_prunedMass_data_copy__10->SetMaximum(3.732e+07);
   DATA__FatJet_prunedMass_data_copy__10->SetEntries(17567);
   DATA__FatJet_prunedMass_data_copy__10->SetDirectory(0);
   DATA__FatJet_prunedMass_data_copy__10->SetFillColor(1);
   DATA__FatJet_prunedMass_data_copy__10->SetFillStyle(0);
   DATA__FatJet_prunedMass_data_copy__10->SetMarkerStyle(20);
   DATA__FatJet_prunedMass_data_copy__10->SetMarkerSize(0.75);
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetTitle("M_{pruned} (AK8 jets) [GeV]");
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetRange(1,13);
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data_copy__10->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data_copy__10->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_prunedMass_data_copy__10->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data_copy__10->GetZaxis()->SetTitle("_data");
   DATA__FatJet_prunedMass_data_copy__10->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_prunedMass_data_copy__10->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_prunedMass_data_copy__10->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_prunedMass_data_copy__10->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_prunedMass_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
