void FatJet_phi_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:35 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-3.855591,-1.545458,3.284392,8.027065);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_phi_data__5 = new TH1D("DATA__FatJet_phi_data__5","",10,-3.141593,3.141593);
   DATA__FatJet_phi_data__5->SetBinContent(1,1811);
   DATA__FatJet_phi_data__5->SetBinContent(2,1796);
   DATA__FatJet_phi_data__5->SetBinContent(3,1788);
   DATA__FatJet_phi_data__5->SetBinContent(4,1723);
   DATA__FatJet_phi_data__5->SetBinContent(5,1825);
   DATA__FatJet_phi_data__5->SetBinContent(6,1707);
   DATA__FatJet_phi_data__5->SetBinContent(7,1638);
   DATA__FatJet_phi_data__5->SetBinContent(8,1698);
   DATA__FatJet_phi_data__5->SetBinContent(9,1824);
   DATA__FatJet_phi_data__5->SetBinContent(10,1753);
   DATA__FatJet_phi_data__5->SetBinError(1,42.55585);
   DATA__FatJet_phi_data__5->SetBinError(2,42.37924);
   DATA__FatJet_phi_data__5->SetBinError(3,42.28475);
   DATA__FatJet_phi_data__5->SetBinError(4,41.50904);
   DATA__FatJet_phi_data__5->SetBinError(5,42.72002);
   DATA__FatJet_phi_data__5->SetBinError(6,41.31586);
   DATA__FatJet_phi_data__5->SetBinError(7,40.47221);
   DATA__FatJet_phi_data__5->SetBinError(8,41.2068);
   DATA__FatJet_phi_data__5->SetBinError(9,42.70831);
   DATA__FatJet_phi_data__5->SetBinError(10,41.86884);
   DATA__FatJet_phi_data__5->SetMinimum(0.5);
   DATA__FatJet_phi_data__5->SetMaximum(1.825e+07);
   DATA__FatJet_phi_data__5->SetEntries(17567);
   DATA__FatJet_phi_data__5->SetFillColor(1);
   DATA__FatJet_phi_data__5->SetFillStyle(0);
   DATA__FatJet_phi_data__5->SetMarkerStyle(20);
   DATA__FatJet_phi_data__5->SetMarkerSize(0.75);
   DATA__FatJet_phi_data__5->GetXaxis()->SetTitle("#phi(all jets)");
   DATA__FatJet_phi_data__5->GetXaxis()->SetRange(1,40);
   DATA__FatJet_phi_data__5->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data__5->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data__5->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data__5->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data__5->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data__5->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data__5->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data__5->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_phi_data__5->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data__5->GetZaxis()->SetTitle("_data");
   DATA__FatJet_phi_data__5->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data__5->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data__5->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data__5->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data__5->Draw("E1X0");
   
   TH1D *DATA__FatJet_phi_data_copy__6 = new TH1D("DATA__FatJet_phi_data_copy__6","",10,-3.141593,3.141593);
   DATA__FatJet_phi_data_copy__6->SetBinContent(1,1811);
   DATA__FatJet_phi_data_copy__6->SetBinContent(2,1796);
   DATA__FatJet_phi_data_copy__6->SetBinContent(3,1788);
   DATA__FatJet_phi_data_copy__6->SetBinContent(4,1723);
   DATA__FatJet_phi_data_copy__6->SetBinContent(5,1825);
   DATA__FatJet_phi_data_copy__6->SetBinContent(6,1707);
   DATA__FatJet_phi_data_copy__6->SetBinContent(7,1638);
   DATA__FatJet_phi_data_copy__6->SetBinContent(8,1698);
   DATA__FatJet_phi_data_copy__6->SetBinContent(9,1824);
   DATA__FatJet_phi_data_copy__6->SetBinContent(10,1753);
   DATA__FatJet_phi_data_copy__6->SetBinError(1,42.55585);
   DATA__FatJet_phi_data_copy__6->SetBinError(2,42.37924);
   DATA__FatJet_phi_data_copy__6->SetBinError(3,42.28475);
   DATA__FatJet_phi_data_copy__6->SetBinError(4,41.50904);
   DATA__FatJet_phi_data_copy__6->SetBinError(5,42.72002);
   DATA__FatJet_phi_data_copy__6->SetBinError(6,41.31586);
   DATA__FatJet_phi_data_copy__6->SetBinError(7,40.47221);
   DATA__FatJet_phi_data_copy__6->SetBinError(8,41.2068);
   DATA__FatJet_phi_data_copy__6->SetBinError(9,42.70831);
   DATA__FatJet_phi_data_copy__6->SetBinError(10,41.86884);
   DATA__FatJet_phi_data_copy__6->SetMinimum(0.5);
   DATA__FatJet_phi_data_copy__6->SetMaximum(1.825e+07);
   DATA__FatJet_phi_data_copy__6->SetEntries(17567);
   DATA__FatJet_phi_data_copy__6->SetDirectory(0);
   DATA__FatJet_phi_data_copy__6->SetFillColor(1);
   DATA__FatJet_phi_data_copy__6->SetFillStyle(0);
   DATA__FatJet_phi_data_copy__6->SetMarkerStyle(20);
   DATA__FatJet_phi_data_copy__6->SetMarkerSize(0.75);
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetTitle("#phi(all jets)");
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetRange(1,40);
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data_copy__6->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data_copy__6->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_phi_data_copy__6->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data_copy__6->GetZaxis()->SetTitle("_data");
   DATA__FatJet_phi_data_copy__6->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_phi_data_copy__6->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_phi_data_copy__6->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_phi_data_copy__6->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_phi_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
