void FatJet_jetNTracks_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:37 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-4.545455,-1.620371,40.90909,8.528406);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_jetNTracks_data__65 = new TH1D("DATA__FatJet_jetNTracks_data__65","",10,0,40);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(1,4);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(2,294);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(3,2378);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(4,5040);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(5,5206);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(6,3001);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(7,1146);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(8,369);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(9,102);
   DATA__FatJet_jetNTracks_data__65->SetBinContent(10,23);
   DATA__FatJet_jetNTracks_data__65->SetBinError(1,2);
   DATA__FatJet_jetNTracks_data__65->SetBinError(2,17.14643);
   DATA__FatJet_jetNTracks_data__65->SetBinError(3,48.76474);
   DATA__FatJet_jetNTracks_data__65->SetBinError(4,70.99296);
   DATA__FatJet_jetNTracks_data__65->SetBinError(5,72.15262);
   DATA__FatJet_jetNTracks_data__65->SetBinError(6,54.78138);
   DATA__FatJet_jetNTracks_data__65->SetBinError(7,33.85262);
   DATA__FatJet_jetNTracks_data__65->SetBinError(8,19.20937);
   DATA__FatJet_jetNTracks_data__65->SetBinError(9,10.0995);
   DATA__FatJet_jetNTracks_data__65->SetBinError(10,4.795832);
   DATA__FatJet_jetNTracks_data__65->SetMinimum(0.5);
   DATA__FatJet_jetNTracks_data__65->SetMaximum(5.206e+07);
   DATA__FatJet_jetNTracks_data__65->SetEntries(17567);
   DATA__FatJet_jetNTracks_data__65->SetFillColor(1);
   DATA__FatJet_jetNTracks_data__65->SetFillStyle(0);
   DATA__FatJet_jetNTracks_data__65->SetMarkerStyle(20);
   DATA__FatJet_jetNTracks_data__65->SetMarkerSize(0.75);
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetTitle("jetNTracks");
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetRange(1,40);
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data__65->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data__65->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_jetNTracks_data__65->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data__65->GetZaxis()->SetTitle("_data");
   DATA__FatJet_jetNTracks_data__65->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data__65->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data__65->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data__65->Draw("E1X0");
   
   TH1D *DATA__FatJet_jetNTracks_data_copy__66 = new TH1D("DATA__FatJet_jetNTracks_data_copy__66","",10,0,40);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(1,4);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(2,294);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(3,2378);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(4,5040);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(5,5206);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(6,3001);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(7,1146);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(8,369);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(9,102);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinContent(10,23);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(1,2);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(2,17.14643);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(3,48.76474);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(4,70.99296);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(5,72.15262);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(6,54.78138);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(7,33.85262);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(8,19.20937);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(9,10.0995);
   DATA__FatJet_jetNTracks_data_copy__66->SetBinError(10,4.795832);
   DATA__FatJet_jetNTracks_data_copy__66->SetMinimum(0.5);
   DATA__FatJet_jetNTracks_data_copy__66->SetMaximum(5.206e+07);
   DATA__FatJet_jetNTracks_data_copy__66->SetEntries(17567);
   DATA__FatJet_jetNTracks_data_copy__66->SetDirectory(0);
   DATA__FatJet_jetNTracks_data_copy__66->SetFillColor(1);
   DATA__FatJet_jetNTracks_data_copy__66->SetFillStyle(0);
   DATA__FatJet_jetNTracks_data_copy__66->SetMarkerStyle(20);
   DATA__FatJet_jetNTracks_data_copy__66->SetMarkerSize(0.75);
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetTitle("jetNTracks");
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetRange(1,40);
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_jetNTracks_data_copy__66->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->GetZaxis()->SetTitle("_data");
   DATA__FatJet_jetNTracks_data_copy__66->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_jetNTracks_data_copy__66->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_jetNTracks_data_copy__66->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_jetNTracks_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
