void FatJet_pt_all_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:35 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-136.3636,-1.650609,1227.273,8.730768);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_pt_all_data__1 = new TH1D("DATA__FatJet_pt_all_data__1","",50,0,5000);
   DATA__FatJet_pt_all_data__1->SetBinContent(4,4223);
   DATA__FatJet_pt_all_data__1->SetBinContent(5,7948);
   DATA__FatJet_pt_all_data__1->SetBinContent(6,3233);
   DATA__FatJet_pt_all_data__1->SetBinContent(7,1207);
   DATA__FatJet_pt_all_data__1->SetBinContent(8,548);
   DATA__FatJet_pt_all_data__1->SetBinContent(9,228);
   DATA__FatJet_pt_all_data__1->SetBinContent(10,82);
   DATA__FatJet_pt_all_data__1->SetBinContent(11,48);
   DATA__FatJet_pt_all_data__1->SetBinContent(12,23);
   DATA__FatJet_pt_all_data__1->SetBinContent(13,10);
   DATA__FatJet_pt_all_data__1->SetBinContent(14,11);
   DATA__FatJet_pt_all_data__1->SetBinContent(15,1);
   DATA__FatJet_pt_all_data__1->SetBinContent(16,1);
   DATA__FatJet_pt_all_data__1->SetBinError(4,64.98461);
   DATA__FatJet_pt_all_data__1->SetBinError(5,89.15156);
   DATA__FatJet_pt_all_data__1->SetBinError(6,56.85948);
   DATA__FatJet_pt_all_data__1->SetBinError(7,34.74191);
   DATA__FatJet_pt_all_data__1->SetBinError(8,23.4094);
   DATA__FatJet_pt_all_data__1->SetBinError(9,15.09967);
   DATA__FatJet_pt_all_data__1->SetBinError(10,9.055385);
   DATA__FatJet_pt_all_data__1->SetBinError(11,6.928203);
   DATA__FatJet_pt_all_data__1->SetBinError(12,4.795832);
   DATA__FatJet_pt_all_data__1->SetBinError(13,3.162278);
   DATA__FatJet_pt_all_data__1->SetBinError(14,3.316625);
   DATA__FatJet_pt_all_data__1->SetBinError(15,1);
   DATA__FatJet_pt_all_data__1->SetBinError(16,1);
   DATA__FatJet_pt_all_data__1->SetMinimum(0.5);
   DATA__FatJet_pt_all_data__1->SetMaximum(7.948e+07);
   DATA__FatJet_pt_all_data__1->SetEntries(17567);
   DATA__FatJet_pt_all_data__1->SetFillColor(1);
   DATA__FatJet_pt_all_data__1->SetFillStyle(0);
   DATA__FatJet_pt_all_data__1->SetMarkerStyle(20);
   DATA__FatJet_pt_all_data__1->SetMarkerSize(0.75);
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetTitle("p_{T}(all jets) [GeV]");
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetRange(1,12);
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data__1->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data__1->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data__1->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data__1->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data__1->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_pt_all_data__1->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data__1->GetZaxis()->SetTitle("_data");
   DATA__FatJet_pt_all_data__1->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data__1->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data__1->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data__1->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data__1->Draw("E1X0");
   
   TH1D *DATA__FatJet_pt_all_data_copy__2 = new TH1D("DATA__FatJet_pt_all_data_copy__2","",50,0,5000);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(4,4223);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(5,7948);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(6,3233);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(7,1207);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(8,548);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(9,228);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(10,82);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(11,48);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(12,23);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(13,10);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(14,11);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(15,1);
   DATA__FatJet_pt_all_data_copy__2->SetBinContent(16,1);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(4,64.98461);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(5,89.15156);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(6,56.85948);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(7,34.74191);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(8,23.4094);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(9,15.09967);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(10,9.055385);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(11,6.928203);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(12,4.795832);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(13,3.162278);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(14,3.316625);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(15,1);
   DATA__FatJet_pt_all_data_copy__2->SetBinError(16,1);
   DATA__FatJet_pt_all_data_copy__2->SetMinimum(0.5);
   DATA__FatJet_pt_all_data_copy__2->SetMaximum(7.948e+07);
   DATA__FatJet_pt_all_data_copy__2->SetEntries(17567);
   DATA__FatJet_pt_all_data_copy__2->SetDirectory(0);
   DATA__FatJet_pt_all_data_copy__2->SetFillColor(1);
   DATA__FatJet_pt_all_data_copy__2->SetFillStyle(0);
   DATA__FatJet_pt_all_data_copy__2->SetMarkerStyle(20);
   DATA__FatJet_pt_all_data_copy__2->SetMarkerSize(0.75);
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetTitle("p_{T}(all jets) [GeV]");
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetRange(1,12);
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data_copy__2->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data_copy__2->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_pt_all_data_copy__2->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data_copy__2->GetZaxis()->SetTitle("_data");
   DATA__FatJet_pt_all_data_copy__2->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_pt_all_data_copy__2->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_pt_all_data_copy__2->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_pt_all_data_copy__2->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_pt_all_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
