void FatJet_eta_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:35 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-3.045455,-1.578383,2.409091,8.247412);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_eta_data__3 = new TH1D("DATA__FatJet_eta_data__3","",12,-2.5,2.3);
   DATA__FatJet_eta_data__3->SetBinContent(1,43);
   DATA__FatJet_eta_data__3->SetBinContent(2,362);
   DATA__FatJet_eta_data__3->SetBinContent(3,842);
   DATA__FatJet_eta_data__3->SetBinContent(4,1544);
   DATA__FatJet_eta_data__3->SetBinContent(5,2629);
   DATA__FatJet_eta_data__3->SetBinContent(6,2838);
   DATA__FatJet_eta_data__3->SetBinContent(7,2893);
   DATA__FatJet_eta_data__3->SetBinContent(8,2644);
   DATA__FatJet_eta_data__3->SetBinContent(9,1866);
   DATA__FatJet_eta_data__3->SetBinContent(10,1095);
   DATA__FatJet_eta_data__3->SetBinContent(11,621);
   DATA__FatJet_eta_data__3->SetBinContent(12,186);
   DATA__FatJet_eta_data__3->SetBinError(1,6.557438);
   DATA__FatJet_eta_data__3->SetBinError(2,19.0263);
   DATA__FatJet_eta_data__3->SetBinError(3,29.01724);
   DATA__FatJet_eta_data__3->SetBinError(4,39.29377);
   DATA__FatJet_eta_data__3->SetBinError(5,51.27377);
   DATA__FatJet_eta_data__3->SetBinError(6,53.27288);
   DATA__FatJet_eta_data__3->SetBinError(7,53.78662);
   DATA__FatJet_eta_data__3->SetBinError(8,51.41984);
   DATA__FatJet_eta_data__3->SetBinError(9,43.19722);
   DATA__FatJet_eta_data__3->SetBinError(10,33.09078);
   DATA__FatJet_eta_data__3->SetBinError(11,24.91987);
   DATA__FatJet_eta_data__3->SetBinError(12,13.63818);
   DATA__FatJet_eta_data__3->SetMinimum(0.5);
   DATA__FatJet_eta_data__3->SetMaximum(2.893e+07);
   DATA__FatJet_eta_data__3->SetEntries(17567);
   DATA__FatJet_eta_data__3->SetFillColor(1);
   DATA__FatJet_eta_data__3->SetFillStyle(0);
   DATA__FatJet_eta_data__3->SetMarkerStyle(20);
   DATA__FatJet_eta_data__3->SetMarkerSize(0.75);
   DATA__FatJet_eta_data__3->GetXaxis()->SetTitle("#eta(all jets)");
   DATA__FatJet_eta_data__3->GetXaxis()->SetRange(1,50);
   DATA__FatJet_eta_data__3->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data__3->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data__3->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data__3->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data__3->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data__3->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data__3->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data__3->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_eta_data__3->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data__3->GetZaxis()->SetTitle("_data");
   DATA__FatJet_eta_data__3->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data__3->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data__3->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data__3->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data__3->Draw("E1X0");
   
   TH1D *DATA__FatJet_eta_data_copy__4 = new TH1D("DATA__FatJet_eta_data_copy__4","",12,-2.5,2.3);
   DATA__FatJet_eta_data_copy__4->SetBinContent(1,43);
   DATA__FatJet_eta_data_copy__4->SetBinContent(2,362);
   DATA__FatJet_eta_data_copy__4->SetBinContent(3,842);
   DATA__FatJet_eta_data_copy__4->SetBinContent(4,1544);
   DATA__FatJet_eta_data_copy__4->SetBinContent(5,2629);
   DATA__FatJet_eta_data_copy__4->SetBinContent(6,2838);
   DATA__FatJet_eta_data_copy__4->SetBinContent(7,2893);
   DATA__FatJet_eta_data_copy__4->SetBinContent(8,2644);
   DATA__FatJet_eta_data_copy__4->SetBinContent(9,1866);
   DATA__FatJet_eta_data_copy__4->SetBinContent(10,1095);
   DATA__FatJet_eta_data_copy__4->SetBinContent(11,621);
   DATA__FatJet_eta_data_copy__4->SetBinContent(12,186);
   DATA__FatJet_eta_data_copy__4->SetBinError(1,6.557438);
   DATA__FatJet_eta_data_copy__4->SetBinError(2,19.0263);
   DATA__FatJet_eta_data_copy__4->SetBinError(3,29.01724);
   DATA__FatJet_eta_data_copy__4->SetBinError(4,39.29377);
   DATA__FatJet_eta_data_copy__4->SetBinError(5,51.27377);
   DATA__FatJet_eta_data_copy__4->SetBinError(6,53.27288);
   DATA__FatJet_eta_data_copy__4->SetBinError(7,53.78662);
   DATA__FatJet_eta_data_copy__4->SetBinError(8,51.41984);
   DATA__FatJet_eta_data_copy__4->SetBinError(9,43.19722);
   DATA__FatJet_eta_data_copy__4->SetBinError(10,33.09078);
   DATA__FatJet_eta_data_copy__4->SetBinError(11,24.91987);
   DATA__FatJet_eta_data_copy__4->SetBinError(12,13.63818);
   DATA__FatJet_eta_data_copy__4->SetMinimum(0.5);
   DATA__FatJet_eta_data_copy__4->SetMaximum(2.893e+07);
   DATA__FatJet_eta_data_copy__4->SetEntries(17567);
   DATA__FatJet_eta_data_copy__4->SetDirectory(0);
   DATA__FatJet_eta_data_copy__4->SetFillColor(1);
   DATA__FatJet_eta_data_copy__4->SetFillStyle(0);
   DATA__FatJet_eta_data_copy__4->SetMarkerStyle(20);
   DATA__FatJet_eta_data_copy__4->SetMarkerSize(0.75);
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetTitle("#eta(all jets)");
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetRange(1,50);
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data_copy__4->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data_copy__4->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_eta_data_copy__4->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data_copy__4->GetZaxis()->SetTitle("_data");
   DATA__FatJet_eta_data_copy__4->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_eta_data_copy__4->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_eta_data_copy__4->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_eta_data_copy__4->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_eta_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
