void FatJet_tau1_vertexEnergyRatio_Log()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Dec 18 16:14:37 2018) by ROOT version6.10/09
   TCanvas *c1 = new TCanvas("c1", "c1",0,0,782,552);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.02);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillColor(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad0
   TPad *pad0 = new TPad("pad0", "pad0",0,0.25,1,1);
   pad0->Draw();
   pad0->cd();
   pad0->Range(-1.545455,-1.631415,3.909091,8.602316);
   pad0->SetFillColor(0);
   pad0->SetBorderMode(0);
   pad0->SetBorderSize(2);
   pad0->SetLogy();
   pad0->SetTickx(1);
   pad0->SetTicky(1);
   pad0->SetRightMargin(0.02);
   pad0->SetTopMargin(0.08);
   pad0->SetBottomMargin(0.13);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   pad0->SetFrameFillStyle(0);
   pad0->SetFrameBorderMode(0);
   
   TH1D *DATA__FatJet_tau1_vertexEnergyRatio_data__53 = new TH1D("DATA__FatJet_tau1_vertexEnergyRatio_data__53","",12,-1,3.8);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(1,1752);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(3,4794);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(4,6076);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(5,2224);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(6,1022);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(7,550);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(8,296);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(9,220);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(10,129);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(11,106);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinContent(12,394);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(1,41.8569);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(3,69.23872);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(4,77.9487);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(5,47.1593);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(6,31.96873);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(7,23.45208);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(8,17.20465);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(9,14.8324);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(10,11.35782);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(11,10.29563);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetBinError(12,19.84943);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetMinimum(0.5);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetMaximum(6.076e+07);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetEntries(17567);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetFillColor(1);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetFillStyle(0);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetMarkerStyle(20);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->SetMarkerSize(0.75);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetTitle("tau1_vertexEnergyRatio");
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetRange(1,100);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetZaxis()->SetTitle("_data");
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data__53->Draw("E1X0");
   
   TH1D *DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54 = new TH1D("DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54","",12,-1,3.8);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(1,1752);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(3,4794);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(4,6076);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(5,2224);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(6,1022);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(7,550);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(8,296);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(9,220);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(10,129);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(11,106);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinContent(12,394);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(1,41.8569);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(3,69.23872);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(4,77.9487);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(5,47.1593);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(6,31.96873);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(7,23.45208);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(8,17.20465);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(9,14.8324);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(10,11.35782);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(11,10.29563);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetBinError(12,19.84943);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetMinimum(0.5);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetMaximum(6.076e+07);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetEntries(17567);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetDirectory(0);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetFillColor(1);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetFillStyle(0);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetMarkerStyle(20);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->SetMarkerSize(0.75);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetTitle("tau1_vertexEnergyRatio");
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetRange(1,100);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetXaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetYaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetYaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetYaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetYaxis()->SetTitleOffset(0);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetYaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetZaxis()->SetTitle("_data");
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetZaxis()->SetLabelFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetZaxis()->SetLabelSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetZaxis()->SetTitleSize(0.035);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->GetZaxis()->SetTitleFont(42);
   DATA__FatJet_tau1_vertexEnergyRatio_data_copy__54->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.65,0.55,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("DATA__FatJet_tau1_vertexEnergyRatio_data","16H  Promptv2,v3 (Ref)","e1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.75);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.98,0.94,"");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.89235,"CMS");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.09199999);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1396,0.78195,"Preliminary");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.06992);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.72,"#splitline{Multijet sample}{Double-muon-tagged AK8 jets}");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.6,"p_{T} (AK8 jets) > 350 GeV");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.055);
   tex->SetLineWidth(2);
   tex->Draw();
   pad0->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "pad1",0,0,1,0.32);
   pad1->Draw();
   pad1->cd();
   pad1->Range(0,0,1,1);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(2);
   pad1->SetGridy();
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetRightMargin(0.02);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.31);
   pad1->SetFrameFillStyle(0);
   pad1->SetFrameBorderMode(0);
   pad1->Modified();
   c1->cd();
      tex = new TLatex(0.72,0.98,"                   (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(13);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
